### ISSUE TITLE
PlatformIO as Continuous Integration tool for embedded projects

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#108]
Aims
------
[PlatformIO](http://platformio.org) is #1 tool for "Cloud Compiling" now. The one missing feature is to allow each developer/script to use PlatformIO in "Continuous Integration" manner. PlatformIO can build embedded projects for the different development platforms (Atmel AVR, Atmel SAM, TI MSP430, TI TIVA, Teensy, (soon Freescale FRDM, NXP LPC, Nordic RF51) and etc).

Requirements
------------------
The main aim is to promote PlatformIO as tool which is the best for "Continuous Integration". It should allow to specify `src` files, `lib` directories and `board`s which PlatformIO should use for running.

Implementation
--------------------

It should be implemented via the new command ``platformio ci [OPTIONS] SRC`` where:
* ``SRC`` is the list with source files/dirs.They should be copied to ``src`` directory in new PlatformIO based project.

Options:
* ``-l, --lib`` the list with source code of libraries which should be copied to ``lib`` directory of PlatformIO project. 
* ``-b, --board`` the list with boards. All tests should be passed over them.

**NOTE**
``src``, ``--lib`` and ``--board`` can be MULTIPLE. [GLOB](http://en.wikipedia.org/wiki/Glob_(programming)) syntax should by allowed. 

Using
-------

For example, let's use this project https://github.com/felis/USB_Host_Shield_2.0. We want to test ``PS3SPP.ino`` example with the different boards/platforms:
```bash
# clone repo and change directory to it
platformio ci --lib="." --board=uno --board=teensy31 --board=due examples/Bluetooth/PS3SPP/PS3SPP.ino
```

Travis CI
-----------

Yep :) PlatformIO could be the best friend of @travis-ci. Example of ``.travis.yml``:
```yml
language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/Bluetooth/PS3SPP/PS3SPP.ino
    - PLATFORMIO_CI_SRC=examples/pl2303/pl2303_gps/pl2303_gps.ino

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci --lib="." --board=uno --board=teensy31 --board=due 
```

----------

We have already implemented a lot of these things... See how does testing work with [PlatformIO Examples](https://github.com/ivankravets/platformio/tree/develop/examples) via Travis CI: 
https://travis-ci.org/ivankravets/platformio/jobs/52805475

----------

Friends @valeros, @aphelps, @robertinant, @PaulStoffregen, @aethaniel, @xxxajk, @Lauszus, @pelikhan, @ncolomer, @bettabacon, @eiginn, @Informatic, @mac7, @manashmndl, @MrCustomizer, @franciscoruiz, @elyulka

What do you think about it?
